// input constants

export const ADD_CHARACTER = 'ADD_CHARACTER';
export const REMOVE_CHARACTER = 'REMOVE_CHARACTER';
export const SELECT_SUGGESTION_LEFT = 'SELECT_SUGGESTION_LEFT';
export const SELECT_SUGGESTION_RIGHT = 'SELECT_SUGGESTION_RIGHT';
export const SUBMIT = 'SUBMIT';
