// input constants

export const SET_DATA = 'SET_DATA';
export const ADD_CHARACTER = 'ADD_CHARACTER';
export const REMOVE_CHARACTER = 'REMOVE_CHARACTER';
export const SELECT_NEXT_SUGGESTION = 'SELECT_NEXT_SUGGESTION';
export const SELECT_PREVIOUS_SUGGESTION = 'SELECT_PREVIOUS_SUGGESTION';
export const SUBMIT = 'SUBMIT';
export const MAX_RESULTS = 7;
